INSERT INTO feedback (source, text, sentiment, theme) VALUES ('support', 'The system is just not working properly for me today, very frustrating experience overall', 'negative', 'system issues');
INSERT INTO feedback (source, text, sentiment, theme) VALUES ('support', 'Having issues with the platform again, this is getting really annoying', 'negative', 'platform problems');
INSERT INTO feedback (source, text, sentiment, theme) VALUES ('github', 'Memory leak issue still not fixed, this has been reported multiple times', 'negative', 'memory leak');
INSERT INTO feedback (source, text, sentiment, theme) VALUES ('github', 'API rate limiting is too aggressive, blocking legitimate usage again', 'negative', 'api limits');
INSERT INTO feedback (source, text, sentiment, theme) VALUES ('twitter', 'Love the new features! Really making my workflow much better', 'positive', 'features');
INSERT INTO feedback (source, text, sentiment, theme) VALUES ('twitter', 'The UI redesign looks amazing, great job team!', 'positive', 'ui design');
INSERT INTO feedback (source, text, sentiment, theme) VALUES ('community', 'Enterprise deployment failing due to authentication issues with SSO provider', 'negative', 'enterprise auth');
INSERT INTO feedback (source, text, sentiment, theme) VALUES ('community', 'Critical: Data corruption detected in bulk import operations for large datasets', 'negative', 'data corruption');
INSERT INTO feedback (source, text, sentiment, theme) VALUES ('community', 'High severity: Security vulnerability in API key management system', 'negative', 'security');
INSERT INTO feedback (source, text, sentiment, theme) VALUES ('community', 'Performance degradation in multi-tenant environment affecting all clients', 'negative', 'performance');
INSERT INTO feedback (source, text, sentiment, theme) VALUES ('support', 'Something is broken but I cannot figure out what exactly, please help', 'negative', 'general issues');
INSERT INTO feedback (source, text, sentiment, theme) VALUES ('support', 'The performance has been terrible lately, making it hard to get work done', 'negative', 'performance');
INSERT INTO feedback (source, text, sentiment, theme) VALUES ('github', 'Documentation still outdated, examples do not match current API', 'negative', 'documentation');
INSERT INTO feedback (source, text, sentiment, theme) VALUES ('github', 'Type definitions are incorrect, causing runtime errors in production', 'negative', 'typescript');
INSERT INTO feedback (source, text, sentiment, theme) VALUES ('twitter', 'Having some trouble with the latest update, rolling back for now', 'negative', 'update issues');
INSERT INTO feedback (source, text, sentiment, theme) VALUES ('twitter', 'Customer support was super helpful today, thank you!', 'positive', 'support');
INSERT INTO feedback (source, text, sentiment, theme) VALUES ('twitter', 'Waiting for the bug fix mentioned in the roadmap', 'neutral', 'bug fixes');
INSERT INTO feedback (source, text, sentiment, theme) VALUES ('support', 'Keep running into errors when trying to save my work', 'negative', 'errors');
INSERT INTO feedback (source, text, sentiment, theme) VALUES ('github', 'Build process keeps failing intermittently, please investigate', 'negative', 'build issues');
INSERT INTO feedback (source, text, sentiment, theme) VALUES ('community', 'Integration with Salesforce connector broken after latest security patch', 'negative', 'integration');